general:
  output_path: '/home/michal/Desktop/Data/C_detection/'
  sample_size: 2000
  sample_split: [0.65, 0.2, 0.15]
  pixel_limit: [500, 1500]
  img_aspect_ratio: [0.5,1]

oval_simulator:
  radius_limit: [10,50]
  ellipse_aspect_ratio: [0.85,1] 
  circle_prob: 1
  line_thickness: [1,1]
  occlusion:
    prob: 1
    range: [0.5, 0.8]

augmentation:
    border_distortion:
      prob: 0
      intensity_range: [0.5,1]
    blur:
      prob: 0
      kernel_size: [1,5]
    noise:
      type_prob: [0.5, 0.5] 
      linear:
        line_range: [100,2000]
        corner_prob: 0.5
      cluster:
        rad_range: [10,200]
